package com.example.englishuser.util;
/*
 * 文件名：Config
 * 作者：created by admin on 2019 五月
 * 描述：
 *
 */

public class Config {

    public static int Type_Independent_Writing = 1;

    public static String txt = "Do you agree or disagree with the following statement? Governments should spend more money in support of the arts than in support of athletics such as state-sponsored Olympic teams. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? It is more important for governments to spend money to improve Internet access than to improve public transportation. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? The rules that societies today expect young people to follow and obey are too strict. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Movies and television have more negative effects than positive effects on the way young people behave. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? All university students should be required to take history courses no matter what their field of study is. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? The ability to maintain friendships with a small number of people over a long period of time is more important for happiness than the ability to make many new friends easily. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Because modern life is very complex, it is essential for young people to have the ability to plan and organize. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? It is important to know about events happening around the world, even if it is unlikely that they will affect your daily life. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? The opinions of celebrities, such as famous entertainers and athletes, are more important to younger people than they are to older people. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? In the past, young people depended too much on their parents to make decisions for them; today young people are better able to make decisions about their own lives. Use specific reasons and examples to support your answer.\n" +
            "Some people believe that when busy parents do not have a lot of time to spend with their children, the best use of that time is to have fun playing games or sports. Others believe that it is best to use that time doing things together that are related to schoolwork. Which of the two approaches do you prefer? Use specific reasons and examples to support your answer.\n" +
            "Imagine that you are in a classroom or a meeting. The teacher or the meeting leader says something incorrect. In your opinion, which of the following is the best thing to do? 1. Interrupt and correct the mistake right away; 2. Wait until the class or meeting is over and the people are gone, and then talk to the teacher or meeting leader; 3. Say nothing.\n" +
            "Workers are more satisfied when they have many different types of tasks to do during the workday than when they do similar tasks all day long. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Teacher were more appreciated and valued by society in the past than they were nowadays. Use specific reasons and examples to support your answer.\n" +
            "Some parents offer their school-age children money for each high grade (mark) they get in school. Do you think this is a good idea?\n" +
            "Do you agree or disagree with the following statement? In the past it was easier to identify what type of career or job would lead to a secure, successful future. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Leadership comes naturally: one cannot learn to be a leader. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statements？Because people are busy doing so many different things, they do very few things well. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? For the successful development of a country, it is more important for a government to send money on the education of very young children (five to ten years old) than to spend money on universities. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Famous entertainers and athletes deserve to have more privacy than they have now. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Educating children is a more difficult task today than it was in the past because they spend so much time on cell phone, online games, and social networking Web site. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? When teachers assign projects on which students must work together, the students learn much more effectively than when they are asked to work alone on projects. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Young people today have no influence on the important decisions that determine the future of society as a whole. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Because the world is changing so quickly, people now are less happy or less satisfied with their lives than people were in the past. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? It is more enjoyable to have a job where you work only three days a week for long hours than to have a job where you work five days a week for shorter hours. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? To improve the quality of education, universities should spend more money on salaries for university professors. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Parents today are more involved in their children’s education than were parents in the past. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? If people have the opportunity to get a secure job, they should take it right away rather than wait for a job that would be more satisfying. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? It is better for children to choose jobs that are similar to their parents’ jobs than to choose jobs that are very different from their parents’ job. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Young people nowadays do not give enough time to helping their communities. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? One of the best ways that parents can help their teenage children prepare for adult life is to encourage them to take a part-time job. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? In today’s world, it is more important to work quickly and risk making mistakes than to work slowly and make sure that everything is correct. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Teachers should not make their social or political views known to students in the classroom. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? For success in a future job, the ability to relate well to people is more important than studying hard in school. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Successful people try new things and take risks rather than only doing what they know how to do well. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? In order to be well-informed, a person must get information from many different news resources. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Students are more influenced by their teachers than by their friends. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Most advertisements make products seem much better thanthey really are. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? The best way to travel is in a group led by a tour guide. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? In order to become financially responsible adults, children should learn to manage their own money at young age. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? People benefit more from traveling in their own country than from traveling to foreign countries. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? The extended family (grandparents, cousins, aunts, and uncles) is less important now than it was in the past. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? It is better to have broad knowledge of many academic subjects than to specialize in one specific subject. Use specific reasons and examples to support your answer.\n" +
            "Some people say that the Internet provides people with a lot of valuable information. Others think access to much information creates problems. Which view do you agree with? Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Playing computer games is a waste of time. Children should not be allowed to play them. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Technology has made children less creative than they were in the past. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Television advertising directed towards young children (aged two to five) should not be allowed. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? It is more important for students to understand ideas and concepts than it is for them to learn facts. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Life today is easier and more comfortable than it was when your grandparents were children. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? People today spend too much time on personal enjoyment-doing things they like to do-rather than doing things they should do. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? In twenty years there will be fewer cars in use than there are today. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? It is more important to keep your old friends than it is to make new friends. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? Always telling the truth is the most important consideration in any relationship between people. Use specific reasons and examples to support your answer.\n" +
            "Do you agree or disagree with the following statement? At universities and colleges, sports and social activities are just as important as classes and libraries and should receive equal financial support. Use specific reasons and examples to support your answer.\n";
}
